### ISSUE TITLE
Bugs - Marshmallow ver

### ISSUE THREAD

**Issue by rorre** [Rendyindo/Flyme_X510-cm#2]
Since this is still BETA, bugs may expected here.

- [x] com.android.phone FC

- [x] RIL (part of com.android.phone)

- [x] Phone reboots at Call Receive

- [ ] LED Notification

- [x] No sound for incoming call

~~**DO NOT ASK ABOUT APN HERE, ITS FLYME CODE BUG**~~ Fixed as per b64ebe5755c14965be085daa71652af7eeda71d9

???

**Comment by Rendyindo** [comment]
fixed all, closed

**Comment by rorre** [comment]
Reopening this due to phone reboot after receiving calls.
Full log: https://puu.sh/x2Ldn/e98f66dc69.log

Fixed OwO

**Comment by rorre** [comment]
Reopening this again, still with call issue.
Changing the command to call `matchesCallFilter(Landroid/os/bundle;)[Z` to `;)Z` causes VerifyError due to no int(s) again.

**Comment by fardinportfolio** [comment]
low ram management on 1gb ram........flashing gapps ram management is ssooooo bbbaaaaaad........ 200/1gb

**Comment by rorre** [comment]
Pretty sure that's not a bug :^)

**Comment by hsagent** [comment]
Hello, no sound notification inCall, but play ringtones in settings....

**Comment by rorre** [comment]
@hsagent working normally here.

**Comment by osby11** [comment]
incoming call. sound not working. for me too.

**Comment by rorre** [comment]
Added Incoming call bug to confirmed bugs.

**Comment by Rendyindo** [comment]
No sound detail:
[full log](https://github.com/Rendyindo/Flyme_X510-cm/files/1343832/penguwu.log)
Part of log:
```09-29 16:32:32.211  1505  1505 W System.err: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: java.lang.NoSuchMethodException: isIncomingCallMultiparty not found at com.android.internal.telephony.gsm.GsmConnection
09-29 16:32:32.213  1505  1505 W System.err: 	at com.meizu.phone.Reflector.invokeMethod(Reflector.java:103)
09-29 16:32:32.214  1505  1505 W System.err: 	at com.meizu.phone.Reflector.invokeMethod(Reflector.java:133)
09-29 16:32:32.214  1505  1505 W System.err: 	at com.meizu.phone.api.wrapper.telephony.ConnectionWrapper.isIncomingCallMultiparty(ConnectionWrapper.java:13)
09-29 16:32:32.214  1505  1505 W System.err: 	at com.android.services.telephony.PstnIncomingCallNotifier.sendIncomingCallIntent(PstnIncomingCallNotifier.java:317)
09-29 16:32:32.214  1505  1505 W System.err: 	at com.android.services.telephony.PstnIncomingCallNotifier.handleNewRingingConnection(PstnIncomingCallNotifier.java:235)
09-29 16:32:32.214  1505  1505 W System.err: 	at com.android.services.telephony.PstnIncomingCallNotifier.-wrap2(PstnIncomingCallNotifier.java)
09-29 16:32:32.214  1505  1505 W System.err: 	at com.android.services.telephony.PstnIncomingCallNotifier$1.handleMessage(PstnIncomingCallNotifier.java:98)
09-29 16:32:32.214  1505  1505 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-29 16:32:32.214  1505  1505 W System.err: 	at android.os.Looper.loop(Looper.java:148)
09-29 16:32:32.214  1505  1505 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
09-29 16:32:32.214  1505  1505 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-29 16:32:32.214  1505  1505 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-29 16:32:32.215  1505  1505 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-29 16:32:32.215  1505  1505 W System.err: Caused by: java.lang.IllegalArgumentException: java.lang.NoSuchMethodException: isIncomingCallMultiparty not found at com.android.internal.telephony.gsm.GsmConnection
09-29 16:32:32.215  1505  1505 W System.err: 	at com.meizu.phone.Reflector.reflectMethod(Reflector.java:240)
09-29 16:32:32.215  1505  1505 W System.err: 	at com.meizu.phone.Reflector.getCachedMethod(Reflector.java:51)
09-29 16:32:32.215  1505  1505 W System.err: 	at com.meizu.phone.Reflector.invokeMethod(Reflector.java:93)
09-29 16:32:32.215  1505  1505 W System.err: 	... 12 more
09-29 16:32:32.215  1505  1505 W System.err: Caused by: java.lang.NoSuchMethodException: isIncomingCallMultiparty not found at com.android.internal.telephony.gsm.GsmConnection
09-29 16:32:32.216  1505  1505 W System.err: 	at com.meizu.phone.Reflector.getMethod(Reflector.java:256)
09-29 16:32:32.216  1505  1505 W System.err: 	at com.meizu.phone.Reflector.reflectMethod(Reflector.java:238)
09-29 16:32:32.216  1505  1505 W System.err: 	... 14 more```

```09-29 16:32:32.456  1505  1505 W System.err: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: java.lang.NoSuchMethodException: registerForSpeechCodecInfo not found at com.android.internal.telephony.gsm.GSMPhone
09-29 16:32:32.460  1505  1505 W System.err: 	at com.meizu.phone.Reflector.invokeMethod(Reflector.java:103)
09-29 16:32:32.460  1505  1505 W System.err: 	at com.meizu.phone.api.wrapper.telephony.PhoneWrapper.registerForSpeechCodecInfo(PhoneWrapper.java:454)
09-29 16:32:32.460  1505  1505 W System.err: 	at com.android.services.telephony.TelephonyConnection.setOriginalConnection(TelephonyConnection.java:903)
09-29 16:32:32.460  1505  1505 W System.err: 	at com.android.services.telephony.TelephonyConnection.<init>(TelephonyConnection.java:551)
09-29 16:32:32.460  1505  1505 W System.err: 	at com.android.services.telephony.GsmConnection.<init>(GsmConnection.java:40)
09-29 16:32:32.460  1505  1505 W System.err: 	at com.android.services.telephony.TelephonyConnectionService.createConnectionFor(TelephonyConnectionService.java:729)
09-29 16:32:32.460  1505  1505 W System.err: 	at com.android.services.telephony.TelephonyConnectionService.onCreateIncomingConnection(TelephonyConnectionService.java:573)
09-29 16:32:32.460  1505  1505 W System.err: 	at android.telecom.ConnectionService.createConnection(ConnectionService.java:719)
09-29 16:32:32.461  1505  1505 W System.err: 	at android.telecom.ConnectionService.-wrap7(ConnectionService.java)
09-29 16:32:32.461  1505  1505 W System.err: 	at android.telecom.ConnectionService$2$1.run(ConnectionService.java:298)
09-29 16:32:32.461  1505  1505 W System.err: 	at android.telecom.ConnectionService.onAccountsInitialized(ConnectionService.java:1274)
09-29 16:32:32.461  1505  1505 W System.err: 	at android.telecom.ConnectionService.-wrap11(ConnectionService.java)
09-29 16:32:32.461  1505  1505 W System.err: 	at android.telecom.ConnectionService$5$1.run(ConnectionService.java:976)
09-29 16:32:32.461  1505  1505 W System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
09-29 16:32:32.461  1505  1505 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-29 16:32:32.461  1505  1505 W System.err: 	at android.os.Looper.loop(Looper.java:148)
09-29 16:32:32.461  1505  1505 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
09-29 16:32:32.462  1505  1505 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-29 16:32:32.467  1505  1505 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-29 16:32:32.467  1505  1505 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-29 16:32:32.467  1505  1505 W System.err: Caused by: java.lang.IllegalArgumentException: java.lang.NoSuchMethodException: registerForSpeechCodecInfo not found at com.android.internal.telephony.gsm.GSMPhone
09-29 16:32:32.468  1505  1505 W System.err: 	at com.meizu.phone.Reflector.reflectMethod(Reflector.java:240)
09-29 16:32:32.468  1505  1505 W System.err: 	at com.meizu.phone.Reflector.getCachedMethod(Reflector.java:51)
09-29 16:32:32.468  1505  1505 W System.err: 	at com.meizu.phone.Reflector.invokeMethod(Reflector.java:93)
09-29 16:32:32.468  1505  1505 W System.err: 	... 19 more
09-29 16:32:32.468  1505  1505 W System.err: Caused by: java.lang.NoSuchMethodException: registerForSpeechCodecInfo not found at com.android.internal.telephony.gsm.GSMPhone
09-29 16:32:32.468  1505  1505 W System.err: 	at com.meizu.phone.Reflector.getMethod(Reflector.java:256)
09-29 16:32:32.469  1505  1505 W System.err: 	at com.meizu.phone.Reflector.reflectMethod(Reflector.java:238)
09-29 16:32:32.469  1505  1505 W System.err: 	... 21 more
09-29 16:32:32.472  1505  1505 W System.err: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: java.lang.NoSuchMethodException: registerForVtStatusInfo not found at com.android.internal.telephony.gsm.GSMPhone
09-29 16:32:32.472  1505  1505 W System.err: 	at com.meizu.phone.Reflector.invokeMethod(Reflector.java:103)
09-29 16:32:32.472  1505  1505 W System.err: 	at com.meizu.phone.api.wrapper.telephony.PhoneWrapper.registerForVtStatusInfo(PhoneWrapper.java:515)
09-29 16:32:32.472  1505  1505 W System.err: 	at com.android.services.telephony.TelephonyConnection.setOriginalConnection(TelephonyConnection.java:907)
09-29 16:32:32.473  1505  1505 W System.err: 	at com.android.services.telephony.TelephonyConnection.<init>(TelephonyConnection.java:551)
09-29 16:32:32.473  1505  1505 W System.err: 	at com.android.services.telephony.GsmConnection.<init>(GsmConnection.java:40)
09-29 16:32:32.473  1505  1505 W System.err: 	at com.android.services.telephony.TelephonyConnectionService.createConnectionFor(TelephonyConnectionService.java:729)
09-29 16:32:32.473  1505  1505 W System.err: 	at com.android.services.telephony.TelephonyConnectionService.onCreateIncomingConnection(TelephonyConnectionService.java:573)
09-29 16:32:32.473  1505  1505 W System.err: 	at android.telecom.ConnectionService.createConnection(ConnectionService.java:719)
09-29 16:32:32.473  1505  1505 W System.err: 	at android.telecom.ConnectionService.-wrap7(ConnectionService.java)
09-29 16:32:32.473  1505  1505 W System.err: 	at android.telecom.ConnectionService$2$1.run(ConnectionService.java:298)
09-29 16:32:32.473  1505  1505 W System.err: 	at android.telecom.ConnectionService.onAccountsInitialized(ConnectionService.java:1274)
09-29 16:32:32.473  1505  1505 W System.err: 	at android.telecom.ConnectionService.-wrap11(ConnectionService.java)
09-29 16:32:32.473  1505  1505 W System.err: 	at android.telecom.ConnectionService$5$1.run(ConnectionService.java:976)
09-29 16:32:32.473  1505  1505 W System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
09-29 16:32:32.473  1505  1505 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-29 16:32:32.474  1505  1505 W System.err: 	at android.os.Looper.loop(Looper.java:148)
09-29 16:32:32.474  1505  1505 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
09-29 16:32:32.474  1505  1505 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-29 16:32:32.474  1505  1505 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-29 16:32:32.474  1505  1505 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-29 16:32:32.474  1505  1505 W System.err: Caused by: java.lang.IllegalArgumentException: java.lang.NoSuchMethodException: registerForVtStatusInfo not found at com.android.internal.telephony.gsm.GSMPhone
09-29 16:32:32.474  1505  1505 W System.err: 	at com.meizu.phone.Reflector.reflectMethod(Reflector.java:240)
09-29 16:32:32.474  1505  1505 W System.err: 	at com.meizu.phone.Reflector.getCachedMethod(Reflector.java:51)
09-29 16:32:32.475  1505  1505 W System.err: 	at com.meizu.phone.Reflector.invokeMethod(Reflector.java:93)
09-29 16:32:32.475  1505  1505 W System.err: 	... 19 more
09-29 16:32:32.481  1505  1505 W System.err: Caused by: java.lang.NoSuchMethodException: registerForVtStatusInfo not found at com.android.internal.telephony.gsm.GSMPhone
09-29 16:32:32.481  1505  1505 W System.err: 	at com.meizu.phone.Reflector.getMethod(Reflector.java:256)
09-29 16:32:32.481  1505  1505 W System.err: 	at com.meizu.phone.Reflector.reflectMethod(Reflector.java:238)
09-29 16:32:32.482  1505  1505 W System.err: 	... 21 more```

```09-29 16:32:33.244  7188  7188 W System.err: java.lang.NoSuchMethodException: resume []
09-29 16:32:33.248  7188  7188 W System.err: 	at java.lang.Class.getMethod(Class.java:624)
09-29 16:32:33.248  7188  7188 W System.err: 	at java.lang.Class.getMethod(Class.java:603)
09-29 16:32:33.248  7188  7188 W System.err: 	at com.android.soundrecorder.utils.q.b(SourceFile:334)
09-29 16:32:33.249  7188  7188 W System.err: 	at com.android.soundrecorder.MediaRecorderService.onCreate(SourceFile:95)
09-29 16:32:33.249  7188  7188 W System.err: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2911)
09-29 16:32:33.249  7188  7188 W System.err: 	at android.app.ActivityThread.-wrap4(ActivityThread.java)
09-29 16:32:33.249  7188  7188 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1446)
09-29 16:32:33.250  7188  7188 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-29 16:32:33.250  7188  7188 W System.err: 	at android.os.Looper.loop(Looper.java:148)
09-29 16:32:33.250  7188  7188 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
09-29 16:32:33.250  7188  7188 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-29 16:32:33.250  7188  7188 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-29 16:32:33.250  7188  7188 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)```

```09-29 16:32:33.295  7188  7188 W System.err: java.lang.NoSuchFieldException: MPEG_3
09-29 16:32:33.296  7188  7188 W System.err: 	at com.android.soundrecorder.utils.q.b(SourceFile:277)
09-29 16:32:33.296  7188  7188 W System.err: 	at com.android.soundrecorder.utils.q.a(SourceFile:304)
09-29 16:32:33.296  7188  7188 W System.err: 	at com.android.soundrecorder.utils.p.b(SourceFile:281)
09-29 16:32:33.296  7188  7188 W System.err: 	at com.android.soundrecorder.MediaRecorderService.onCreate(SourceFile:106)
09-29 16:32:33.296  7188  7188 W System.err: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2911)
09-29 16:32:33.297  7188  7188 W System.err: 	at android.app.ActivityThread.-wrap4(ActivityThread.java)
09-29 16:32:33.297  7188  7188 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1446)
09-29 16:32:33.297  7188  7188 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-29 16:32:33.297  7188  7188 W System.err: 	at android.os.Looper.loop(Looper.java:148)
09-29 16:32:33.297  7188  7188 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
09-29 16:32:33.297  7188  7188 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-29 16:32:33.297  7188  7188 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-29 16:32:33.298  7188  7188 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-29 16:32:33.299  7188  7188 W System.err: java.lang.NoSuchFieldException: MPEG_3
09-29 16:32:33.300  7188  7188 W System.err: 	at com.android.soundrecorder.utils.q.b(SourceFile:277)
09-29 16:32:33.300  7188  7188 W System.err: 	at com.android.soundrecorder.utils.q.a(SourceFile:304)
09-29 16:32:33.300  7188  7188 W System.err: 	at com.android.soundrecorder.utils.p.c(SourceFile:297)
09-29 16:32:33.300  7188  7188 W System.err: 	at com.android.soundrecorder.MediaRecorderService.onCreate(SourceFile:107)
09-29 16:32:33.301  7188  7188 W System.err: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2911)
09-29 16:32:33.301  7188  7188 W System.err: 	at android.app.ActivityThread.-wrap4(ActivityThread.java)
09-29 16:32:33.301  7188  7188 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1446)
09-29 16:32:33.301  7188  7188 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-29 16:32:33.301  7188  7188 W System.err: 	at android.os.Looper.loop(Looper.java:148)
09-29 16:32:33.302  7188  7188 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
09-29 16:32:33.302  7188  7188 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
09-29 16:32:33.302  7188  7188 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-29 16:32:33.302  7188  7188 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)```

**Comment by rawmain** [comment]
Thanks to Engineer Mr. Zou Junhua, I've applied the following patch to NotificationManager.smali for my latest ROM Build (20171227) : 

https://github.com/rawmain/flyme-l861/commit/aebe7daebdaee83d18ff2d347f2fe316d60dc53b

- Vibration now is working for incoming calls
- Volume still low for ringtone alerts

**Comment by rorre** [comment]
thanks for the info!

**Comment by zainarbani** [comment]
Kernel Please @Rendyindo

**Comment by rorre** [comment]
@zainarbani it's stock 3.18.19

**Comment by zainarbani** [comment]
@Rendyindo Bro please fix touch panel on infinix hot 2 custom kernel 3.10.x
And please add hxd8394 lcm on 3.18.x source.

**Comment by zainarbani** [comment]
Its diificult to apply hxd8394 one on 3.18.x  source, i always get error on dsi_cmd...

**Comment by zainarbani** [comment]
solved touch panel on Mystery kernel 3.10.x for 2nd LCM, but speaker and camera driver still missing.

Also implementing 2nd LCM on Mystery kernel 3.18.x , its booted but touch panel not working and blinking LCD when touched then reboot.
Please help me @Rendyindo @Mysteryagr @iykequame

**Comment by Mysteryagr** [comment]
@zainarbani 
Me and Rendy already did this, what did you do new? What is what you added? I fixed touch on kernel 3.10.x but the same configuration didn't work on kernel 3.18.x , and Rendy fixed the second LCM driver.
Same state, and same bugs.. and we couldn't fix the rest because the drivers are not available and cannot be found in other kernel sources.

**Comment by rorre** [comment]
Offtopic, please go to this repo https://github.com/Infinix-Hot-2/Mystery-Kernel-3.10.x
