### ISSUE TITLE
[HELP] Flyme 6 system crashes

### ISSUE THREAD

**Issue by sostk** [Rendyindo/Flyme_X510-cm#5]
Hi the sytem ui crashes after finishing booting.Can you help me.

(RendyAK)
[logcat.txt](https://github.com/Rendyindo/Flyme_X510-cm/files/1182721/flyme6_2.txt)
[tombstone](https://transfer.sh/f4IPT/log.txt)

**Comment by rorre** [comment]
do the system is rooted?
seems like it can't access /cache..

**Comment by rorre** [comment]
if that doesn't work too, try to use permissive SELinux

**Comment by sostk** [comment]
yup it is rooted from  su file of cyanogenmod

**Comment by rorre** [comment]
okok, now can you zip **the whole** tombstones folder? and send it here.

**Comment by sostk** [comment]
[tombstones.zip](https://github.com/Rendyindo/Flyme_X510-cm/files/1184634/tombstones.zip)

**Comment by rorre** [comment]
What I can find is only
```
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: auto update
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: java.io.FileNotFoundException: /cache/.update_auto: open failed: ENOENT (No such file or directory)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at libcore.io.IoBridge.open(IoBridge.java:452)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at java.io.FileInputStream.<init>(FileInputStream.java:76)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at java.io.FileInputStream.<init>(FileInputStream.java:103)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at java.io.FileReader.<init>(FileReader.java:66)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at com.android.systemui.keyguard.KeyguardViewMediator.isAutoUpdate(KeyguardViewMediator.java:2423)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at com.android.systemui.keyguard.KeyguardViewMediator.onBootCompleted(KeyguardViewMediator.java:1920)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:162)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at com.android.systemui.keyguard.KeyguardService.onCreate(KeyguardService.java:43)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2911)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at android.app.ActivityThread.-wrap4(ActivityThread.java)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1446)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at android.os.Looper.loop(Looper.java:148)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at java.lang.reflect.Method.invoke(Native Method)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at libcore.io.Posix.open(Native Method)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	at libcore.io.IoBridge.open(IoBridge.java:438)
01-12 09:42:56.016 11987 11987 D KeyguardViewMediator: 	... 16 more
```
which makes no sense

**Comment by sostk** [comment]
isnt it crashing systemui?

**Comment by rorre** [comment]
yea, it is, probaly, but well, its better to ask it in [FlymeOS/manifest issues](https://github.com/FlymeOS/manifest/issues) becouse I dont how to fix it, sorry.

**Comment by sostk** [comment]
ok no worries.

**Comment by aymende7** [comment]
@Rendyindo [SystemServer.smali.zip](https://github.com/Rendyindo/Flyme_X510-cm/files/1184871/SystemServer.smali.zip)

**Comment by aymende7** [comment]
@sostk i've found this
https://github.com/FlymeOS/devices-base_cm/commit/82615457e780e52e999701ab0d961633cd388fe5

**Comment by sostk** [comment]
I did that

**Comment by rorre** [comment]
issue already opened https://github.com/FlymeOS/devices-base_cm/issues/16
closing this.
