### ISSUE TITLE
RIL not working

### ISSUE THREAD

**Issue by rorre** [Rendyindo/Flyme_X510-cm#6]
```12-20 23:57:32.842  2931  2931 E AndroidRuntime: FATAL EXCEPTION: main
12-20 23:57:32.842  2931  2931 E AndroidRuntime: Process: com.android.phone, PID: 2931
12-20 23:57:32.842  2931  2931 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.android.phone.PhoneApp: android.content.res.Resources$NotFoundException: String array resource ID #0x0
12-20 23:57:32.842  2931  2931 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5501)
12-20 23:57:32.842  2931  2931 E AndroidRuntime: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
12-20 23:57:32.842  2931  2931 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1575)
12-20 23:57:32.842  2931  2931 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-20 23:57:32.842  2931  2931 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
12-20 23:57:32.842  2931  2931 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6236)
12-20 23:57:32.842  2931  2931 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-20 23:57:32.842  2931  2931 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
12-20 23:57:32.842  2931  2931 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
12-20 23:57:32.842  2931  2931 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: String array resource ID #0x0
12-20 23:57:32.842  2931  2931 E AndroidRuntime: 	at android.content.res.Resources.getStringArray(Resources.java:525)
12-20 23:57:32.842  2931  2931 E AndroidRuntime: 	at com.mediatek.phone.PhoneInterfaceManagerEx.omhInit(PhoneInterfaceManagerEx.java:2394)
12-20 23:57:32.842  2931  2931 E AndroidRuntime: 	at com.mediatek.phone.PhoneInterfaceManagerEx.<init>(PhoneInterfaceManagerEx.java:431)
12-20 23:57:32.842  2931  2931 E AndroidRuntime: 	at com.mediatek.phone.PhoneInterfaceManagerEx.init(PhoneInterfaceManagerEx.java:410)
12-20 23:57:32.842  2931  2931 E AndroidRuntime: 	at com.android.phone.PhoneGlobals.onCreate(PhoneGlobals.java:464)
12-20 23:57:32.842  2931  2931 E AndroidRuntime: 	at com.android.phone.PhoneApp.onCreate(PhoneApp.java:50)
12-20 23:57:32.842  2931  2931 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
12-20 23:57:32.842  2931  2931 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5498)
12-20 23:57:32.842  2931  2931 E AndroidRuntime: 	... 8 more```

**Comment by rorre** [comment]
~~This is really weird since I've disabled the com.mediatek.phone.PhoneInterfaceManagerEx.omhInit calling command in PhoneInterfaceManageEx.smali, take a look at https://github.com/Rendyindo/Flyme_X510-cm/blob/nougat-7.1/TeleService/smali/com/mediatek/phone/PhoneInterfaceManagerEx.smali.part#L97~~ ok I dunno but I disabled it again manually, but still, RIL doesn't work.
[logcat](https://github.com/Rendyindo/Flyme_X510-cm/files/1577907/log.txt)

**Comment by rorre** [comment]
Resolved
